// Integrations & Extensions

// 🔌 Плагіни для VS Code
function generateVSCodeExtension() {
    if (Object.keys(codeFiles).length === 0) {
        alert('⚠️ Спочатку згенеруй якийсь код!');
        return;
    }
    
    const extensionCode = `{
  "name": "ai-hub-project",
  "displayName": "AI Hub Generated Project",
  "description": "Project generated by AI Assistant Hub",
  "version": "1.0.0",
  "engines": {
    "vscode": "^1.60.0"
  },
  "categories": ["Other"],
  "activationEvents": ["onStartupFinished"],
  "main": "./extension.js",
  "contributes": {
    "commands": [{
      "command": "extension.preview",
      "title": "Preview Project"
    }]
  }
}`;
    
    const blob = new Blob([extensionCode], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'package.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    alert('✅ VS Code конфігурацію створено!');
}

// 🌐 Розширення для браузера (Chrome Extension)
function generateBrowserExtension() {
    if (Object.keys(codeFiles).length === 0) {
        alert('⚠️ Спочатку згенеруй HTML код!');
        return;
    }
    
    const manifest = {
        "manifest_version": 3,
        "name": "AI Hub Extension",
        "version": "1.0",
        "description": "Generated by AI Assistant Hub",
        "action": {
            "default_popup": "index.html"
        },
        "permissions": ["storage"]
    };
    
    const manifestBlob = new Blob([JSON.stringify(manifest, null, 2)], { type: 'application/json' });
    const manifestUrl = URL.createObjectURL(manifestBlob);
    const a = document.createElement('a');
    a.href = manifestUrl;
    a.download = 'manifest.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(manifestUrl);
    
    alert('✅ Chrome Extension manifest створено!\n\nТепер завантаж всі файли та запакуй у ZIP для публікації.');
}

// 📱 PWA (Progressive Web App)
async function generatePWA() {
    if (Object.keys(codeFiles).length === 0) {
        alert('⚠️ Спочатку згенеруй HTML/JS/CSS код!');
        return;
    }
    
    // Service Worker
    const serviceWorker = `
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('ai-hub-v1').then((cache) => {
      return cache.addAll([
        '/',
        '/index.html',
        '/styles.css',
        '/script.js'
      ]);
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
`;
    
    // Manifest.json для PWA
    const manifest = {
        "name": "AI Hub PWA",
        "short_name": "AI Hub",
        "description": "Progressive Web App generated by AI Assistant Hub",
        "start_url": "/",
        "display": "standalone",
        "background_color": "#0a0a0f",
        "theme_color": "#667eea",
        "icons": [
            {
                "src": "/icon-192.png",
                "sizes": "192x192",
                "type": "image/png"
            },
            {
                "src": "/icon-512.png",
                "sizes": "512x512",
                "type": "image/png"
            }
        ]
    };
    
    // Створити ZIP з PWA файлами
    const zip = new JSZip();
    zip.file('service-worker.js', serviceWorker);
    zip.file('manifest.json', JSON.stringify(manifest, null, 2));
    
    // Додати існуючі файли
    Object.keys(codeFiles).forEach(filename => {
        zip.file(filename, codeFiles[filename].code);
    });
    
    const content = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(content);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'pwa-project.zip';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    alert('✅ PWA проект створено!\n\nЗавантаж ZIP та розпакуй для тестування.');
}

// 🐙 GitHub Integration
function exportToGitHub() {
    if (Object.keys(codeFiles).length === 0) {
        alert('⚠️ Немає коду для експорту!');
        return;
    }
    
    const repoName = prompt('Введіть назву GitHub репозиторія:', 'ai-hub-project');
    if (!repoName) return;
    
    // Створити README.md
    let readme = `# ${repoName}\n\n`;
    readme += `🤖 Проект згенеровано через AI Assistant Hub\n\n`;
    readme += `## 📁 Файли проекту:\n\n`;
    
    Object.keys(codeFiles).forEach(filename => {
        readme += `- \`${filename}\` (${codeFiles[filename].language})\n`;
    });
    
    readme += `\n## 🚀 Як запустити:\n\n`;
    readme += `1. Клонуй репозиторій\n`;
    readme += `2. Відкрий \`index.html\` у браузері\n`;
    readme += `3. Enjoy! 🎉\n`;
    
    // Завантажити README
    const blob = new Blob([readme], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'README.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    alert(`✅ README.md створено!\n\nТепер:\n1. Створи репозиторій "${repoName}" на GitHub\n2. Завантаж усі файли\n3. git add . && git commit -m "Initial commit" && git push`);
}

// Додати кнопки інтеграції до UI
function initializeIntegrations() {
    const codeActions = document.querySelector('.code-actions');
    if (!codeActions) return;
    
    // Очистити існуючі кнопки інтеграцій якщо є
    const existingIntegrations = document.getElementById('integration-buttons');
    if (existingIntegrations) {
        existingIntegrations.remove();
    }
    
    const integrationsDiv = document.createElement('div');
    integrationsDiv.id = 'integration-buttons';
    integrationsDiv.style.display = 'flex';
    integrationsDiv.style.gap = '8px';
    integrationsDiv.style.marginLeft = '10px';
    
    integrationsDiv.innerHTML = `
        <button onclick="generatePWA()" title="Створити PWA">📱 PWA</button>
        <button onclick="generateBrowserExtension()" title="Створити розширення для браузера">🌐 Extension</button>
        <button onclick="exportToGitHub()" title="Експорт на GitHub">🐙 GitHub</button>
    `;
    
    codeActions.appendChild(integrationsDiv);
}
